import type { ParsedOperation, ResolvedConfig } from '../types.js';

export function generateIndexFile(operations: ParsedOperation[], _config: ResolvedConfig): string {
  const exportSet = new Set<string>();
  for (const operation of operations) {
    exportSet.add(`export * from "./${operation.moduleName}/${operation.fileBaseName}";`);
  }

  return `/* eslint-disable */
// Auto-generated by swgto.
${[...exportSet].join('\n')}
`;
}
