import type { ParsedOperation, ResolvedConfig } from '../types.js';

export function generateIndexFile(operations: ParsedOperation[], config: ResolvedConfig): string {
  const exports = operations.map((operation) => {
    return `export * from "./${operation.moduleName}/${operation.fileBaseName}";`;
  });

  return `/* eslint-disable */
// Auto-generated by swgto.
${exports.join('\n')}
`;
}
