import type { ParsedOperation } from '../types.js';

function isSimpleTypeRef(name: string): boolean {
  return /^[\w.]+$/.test(name)
}

function buildParamTag(requestParamType: string, typeImportPath: string): string {
  if (requestParamType === 'void') return '[params]'

  // Named type reference (e.g. GetUserParams) → {import("../types").GetUserParams} params
  if (isSimpleTypeRef(requestParamType)) {
    return `{import(${JSON.stringify(typeImportPath)}).${requestParamType}} params`
  }

  // Inline type expression (e.g. { taskId: number } & { id: string }) → use directly without import()
  return `{${requestParamType}} params`
}

function buildFunctionDoc(operation: ParsedOperation, typeImportPath: string, requestParamType: string): string {
  const lines: string[] = [];

  if (operation.summary) {
    lines.push(operation.summary);
  }

  if (operation.description) {
    lines.push(operation.description);
  }

  lines.push(`@path ${operation.path}`);
  lines.push(`@requestPath ${operation.requestPath}`);
  lines.push(`@method ${operation.method.toUpperCase()}`);
  lines.push(`@param ${buildParamTag(requestParamType, typeImportPath)}`);
  lines.push('@param [config]');
  if (operation.responseTypeName) {
    lines.push(`@returns {Promise<import(${JSON.stringify(typeImportPath)}).${operation.responseTypeName}>}`);
  } else {
    lines.push('@template T');
    lines.push('@returns {Promise<T>}');
  }

  return ['/**', ...lines.map((line) => ` * ${line}`), ' */'].join('\n');
}

function renderFunction(operation: ParsedOperation, useGenericUrl: boolean, mergeParams: boolean, flattenOnGet: boolean = false): string {
  const effectiveMerge = mergeParams || (flattenOnGet && operation.method === 'get');
  const queryLine = operation.queryParams.length
    ? `    params: ${effectiveMerge ? 'params' : 'params?.query'},\n`
    : '';
  const bodyOnly = Boolean(operation.requestBodySchema) && !operation.queryParams.length && !operation.pathParams.length;

  // When effectiveMerge=true with path params, extract path keys so they don't leak into body
  const hasBodySchema = Boolean(operation.requestBodySchema);
  const needsCleanData = effectiveMerge && hasBodySchema && operation.pathParams.length > 0;
  const destructureLine = needsCleanData
    ? `  const { ${operation.pathParams.map((p) => p.name).join(', ')}, ...requestData } = params;\n`
    : '';
  const dataValue = needsCleanData ? 'requestData' : effectiveMerge ? 'params' : (bodyOnly ? 'params' : 'params?.body');

  const bodyLine = hasBodySchema ? `    data: ${dataValue},\n` : '';
  const pathArg = effectiveMerge ? 'params' : 'params?.path';
  const urlValue = useGenericUrl && operation.pathParams.length
    ? `buildUrl(${JSON.stringify(operation.requestPath)}, ${pathArg})`
    : operation.pathParams.length
      ? `buildUrl(${pathArg})`
      : JSON.stringify(operation.requestPath);
  const pathLine = `    url: ${urlValue},\n`;

  return `export async function ${operation.functionName}(params, config) {
${destructureLine}  return request({
${pathLine}    method: ${JSON.stringify(operation.method)},
${queryLine}${bodyLine}    ...config,
  });
}`;
}

export function generateJsRequestFile(operation: ParsedOperation, httpClientPath: string, typeImportPath: string, mergeParams: boolean = false, flattenOnGet: boolean = false): string {
  const effectiveMerge = mergeParams || (flattenOnGet && operation.method === 'get');
  const requestParamType = operation.requestTypeExpression ?? 'void';
  const queryLine = operation.queryParams.length
    ? `    params: ${effectiveMerge ? 'params' : 'params?.query'},\n`
    : '';
  const bodyOnly = Boolean(operation.requestBodySchema) && !operation.queryParams.length && !operation.pathParams.length;

  // When effectiveMerge=true with path params, extract path keys so they don't leak into body
  const hasBodySchema = Boolean(operation.requestBodySchema);
  const needsCleanData = effectiveMerge && hasBodySchema && operation.pathParams.length > 0;
  const destructureLine = needsCleanData
    ? `  const { ${operation.pathParams.map((p) => p.name).join(', ')}, ...requestData } = params;\n`
    : '';
  const dataValue = needsCleanData ? 'requestData' : effectiveMerge ? 'params' : (bodyOnly ? 'params' : 'params?.body');

  const bodyLine = hasBodySchema ? `    data: ${dataValue},\n` : '';
  const pathArg = effectiveMerge ? 'params' : 'params?.path';
  const pathLine = operation.pathParams.length ? `    url: buildUrl(${pathArg}),\n` : `    url: ${JSON.stringify(operation.requestPath)},\n`;
  const buildUrlHelper = operation.pathParams.length
    ? `
function buildUrl(path) {
  return ${JSON.stringify(operation.requestPath)}.replace(/\\{([^}]+)\\}/g, (_, key) => String(path?.[key] ?? ''));
}
`
    : '';

  return `/* eslint-disable */
// Auto-generated by swgto.
import request from ${JSON.stringify(httpClientPath)};
${buildUrlHelper}

${buildFunctionDoc(operation, typeImportPath, requestParamType)}
export async function ${operation.functionName}(params, config) {
${destructureLine}  return request({
${pathLine}    method: ${JSON.stringify(operation.method)},
${queryLine}${bodyLine}    ...config,
  });
}
`;
}

export function generateJsModuleFile(operations: ParsedOperation[], httpClientPath: string, typeImportPath: string, mergeParams: boolean = false, flattenOnGet: boolean = false): string {
  const needsBuildUrl = operations.some((op) => op.pathParams.length > 0);
  const buildUrlHelper = needsBuildUrl
    ? `
function buildUrl(url, path) {
  return url.replace(/\\{([^}]+)\\}/g, (_, key) => String(path?.[key] ?? ''));
}
`
    : '';

  const functions = operations.map((op) => {
    const doc = buildFunctionDoc(op, typeImportPath, op.requestTypeExpression ?? 'void');
    return `${doc}\n\n${renderFunction(op, true, mergeParams, flattenOnGet)}`;
  }).join('\n\n');

  return `/* eslint-disable */
// Auto-generated by swgto.
import request from ${JSON.stringify(httpClientPath)};
${buildUrlHelper}
${functions}
`;
}
