import type { ParsedOperation } from '../types.js';

function buildFunctionDoc(operation: ParsedOperation, typeImportPath: string, requestParamType: string): string {
  const lines: string[] = [];

  if (operation.summary) {
    lines.push(operation.summary);
  }

  if (operation.description) {
    lines.push(operation.description);
  }

  lines.push(`@path ${operation.path}`);
  lines.push(`@requestPath ${operation.requestPath}`);
  lines.push(`@method ${operation.method.toUpperCase()}`);
  lines.push(`@param ${requestParamType === 'void' ? '[params]' : `{import(${JSON.stringify(typeImportPath)}).${requestParamType}} params`}`);
  lines.push('@param [config]');
  if (operation.responseTypeName) {
    lines.push(`@returns {Promise<import(${JSON.stringify(typeImportPath)}).${operation.responseTypeName}>}`);
  } else {
    lines.push('@template T');
    lines.push('@returns {Promise<T>}');
  }

  return ['/**', ...lines.map((line) => ` * ${line}`), ' */'].join('\n');
}

function renderFunction(operation: ParsedOperation, useGenericUrl: boolean, mergeParams: boolean): string {
  const queryLine = operation.queryParams.length
    ? `    params: ${mergeParams ? 'params' : 'params?.query'},\n`
    : '';
  const bodyOnly = Boolean(operation.requestBodySchema) && !operation.queryParams.length && !operation.pathParams.length;
  const bodyLine = operation.requestBodySchema
    ? `    data: ${mergeParams ? 'params' : (bodyOnly ? 'params' : 'params?.body')},\n`
    : '';
  const pathArg = mergeParams ? 'params' : 'params?.path';
  const urlValue = useGenericUrl && operation.pathParams.length
    ? `buildUrl(${JSON.stringify(operation.requestPath)}, ${pathArg})`
    : operation.pathParams.length
      ? `buildUrl(${pathArg})`
      : JSON.stringify(operation.requestPath);
  const pathLine = `    url: ${urlValue},\n`;

  return `export async function ${operation.functionName}(params, config) {
  return request({
${pathLine}    method: ${JSON.stringify(operation.method)},
${queryLine}${bodyLine}    ...config,
  });
}`;
}

export function generateJsRequestFile(operation: ParsedOperation, httpClientPath: string, typeImportPath: string, mergeParams: boolean = false): string {
  const requestParamType = operation.requestTypeExpression ?? 'void';
  const queryLine = operation.queryParams.length
    ? `    params: ${mergeParams ? 'params' : 'params?.query'},\n`
    : '';
  const bodyOnly = Boolean(operation.requestBodySchema) && !operation.queryParams.length && !operation.pathParams.length;
  const bodyLine = operation.requestBodySchema
    ? `    data: ${mergeParams ? 'params' : (bodyOnly ? 'params' : 'params?.body')},\n`
    : '';
  const pathArg = mergeParams ? 'params' : 'params?.path';
  const pathLine = operation.pathParams.length ? `    url: buildUrl(${pathArg}),\n` : `    url: ${JSON.stringify(operation.requestPath)},\n`;
  const buildUrlHelper = operation.pathParams.length
    ? `
function buildUrl(path) {
  return ${JSON.stringify(operation.requestPath)}.replace(/\\{([^}]+)\\}/g, (_, key) => String(path?.[key] ?? ''));
}
`
    : '';

  return `/* eslint-disable */
// Auto-generated by swgto.
import request from ${JSON.stringify(httpClientPath)};
${buildUrlHelper}

${buildFunctionDoc(operation, typeImportPath, requestParamType)}
export async function ${operation.functionName}(params, config) {
  return request({
${pathLine}    method: ${JSON.stringify(operation.method)},
${queryLine}${bodyLine}    ...config,
  });
}
`;
}

export function generateJsModuleFile(operations: ParsedOperation[], httpClientPath: string, typeImportPath: string, mergeParams: boolean = false): string {
  const needsBuildUrl = operations.some((op) => op.pathParams.length > 0);
  const buildUrlHelper = needsBuildUrl
    ? `
function buildUrl(url, path) {
  return url.replace(/\\{([^}]+)\\}/g, (_, key) => String(path?.[key] ?? ''));
}
`
    : '';

  const functions = operations.map((op) => {
    const doc = buildFunctionDoc(op, typeImportPath, op.requestTypeExpression ?? 'void');
    return `${doc}\n\n${renderFunction(op, true, mergeParams)}`;
  }).join('\n\n');

  return `/* eslint-disable */
// Auto-generated by swgto.
import request from ${JSON.stringify(httpClientPath)};
${buildUrlHelper}
${functions}
`;
}
