import type { ParsedOperation } from '../types.js';

function buildFunctionDoc(operation: ParsedOperation): string {
  const lines = [
    operation.summary,
    operation.description,
    `@path ${operation.path}`,
    `@requestPath ${operation.requestPath}`,
    `@method ${operation.method.toUpperCase()}`,
  ].filter((value): value is string => Boolean(value));

  if (!lines.length) {
    return '';
  }

  return ['/**', ...lines.map((line) => ` * ${line}`), ' */', ''].join('\n');
}

export function generateTsRequestFile(operation: ParsedOperation, httpClientPath: string, typeImportPath: string): string {
  const importTypes = [
    operation.requestTypeName,
    operation.responseTypeName,
    'RequestConfig',
  ].filter((value, index, array): value is string => Boolean(value) && array.indexOf(value) === index);
  const importLine = importTypes.length
    ? `import type { ${importTypes.join(', ')} } from ${JSON.stringify(typeImportPath)};\n`
    : '';
  const requestArg = operation.requestTypeName ? `params: ${operation.requestTypeName}, config?: RequestConfig` : 'params?: void, config?: RequestConfig';
  const defaultResponseType = operation.responseTypeName ?? 'unknown';
  const bodyLine = operation.requestBodySchema
    ? '    data: params?.body,\n'
    : '';
  const queryLine = operation.queryParams.length ? '    params: params?.query,\n' : '';
  const pathLine = operation.pathParams.length ? '    url: buildUrl(params?.path),\n' : `    url: ${JSON.stringify(operation.requestPath)},\n`;
  const buildUrlHelper = operation.pathParams.length
    ? `
function buildUrl(path?: Record<string, unknown>): string {
  return ${JSON.stringify(operation.requestPath)}.replace(/\\{([^}]+)\\}/g, (_, key) => String(path?.[key] ?? ''));
}
`
    : '';

  return `/* eslint-disable */
// Auto-generated by swgto.
import request from ${JSON.stringify(httpClientPath)};
${importLine}
${buildUrlHelper}
${buildFunctionDoc(operation)}
export async function ${operation.functionName}<T = ${defaultResponseType}>(${requestArg}): Promise<T> {
  return request<T>({
${pathLine}    method: ${JSON.stringify(operation.method)},
${queryLine}${bodyLine}    ...config,
  });
}
`;
}
