import type { ParsedOperation } from '../types.js'

function buildFunctionDoc(operation: ParsedOperation): string {
  const lines = [
    operation.summary,
    operation.description,
    `@path ${operation.path}`,
    `@requestPath ${operation.requestPath}`,
    `@method ${operation.method.toUpperCase()}`,
  ].filter((value): value is string => Boolean(value))

  if (!lines.length) {
    return ''
  }

  return ['/**', ...lines.map((line) => ` * ${line}`), ' */', ''].join('\n')
}

function renderFunction(operation: ParsedOperation, useGenericUrl: boolean, mergeParams: boolean, flattenOnGet: boolean = false): string {
  const effectiveMerge = mergeParams || (flattenOnGet && operation.method === 'get');
  const requestArg = operation.requestTypeExpression
    ? `params: ${operation.requestTypeExpression}, config?: RequestConfig`
    : 'params?: void, config?: RequestConfig'
  const defaultResponseType = operation.responseTypeName ?? 'unknown'
  const bodyOnly = Boolean(operation.requestBodySchema) && !operation.queryParams.length && !operation.pathParams.length

  // When effectiveMerge=true with path params, extract path keys so they don't leak into body
  const hasBodySchema = Boolean(operation.requestBodySchema)
  const needsCleanData = effectiveMerge && hasBodySchema && operation.pathParams.length > 0
  const destructureLine = needsCleanData
    ? `  const { ${operation.pathParams.map((p) => p.name).join(', ')}, ...requestData } = params;\n`
    : ''
  const dataValue = needsCleanData ? 'requestData' : effectiveMerge ? 'params' : bodyOnly ? 'params' : 'params?.body'

  const bodyLine = hasBodySchema ? `    data: ${dataValue},\n` : ''
  const queryLine = operation.queryParams.length ? `    params: ${effectiveMerge ? 'params' : 'params?.query'},\n` : ''
  const pathArg = effectiveMerge ? 'params' : 'params?.path'
  const urlValue =
    useGenericUrl && operation.pathParams.length
      ? `buildUrl(${JSON.stringify(operation.requestPath)}, ${pathArg})`
      : operation.pathParams.length
        ? `buildUrl(${pathArg})`
        : JSON.stringify(operation.requestPath)
  const pathLine = `    url: ${urlValue},\n`

  return `${buildFunctionDoc(operation)}export async function ${operation.functionName}<T = ${defaultResponseType}>(${requestArg}): Promise<T> {
${destructureLine}  return request<T>({
${pathLine}    method: ${JSON.stringify(operation.method)},
${queryLine}${bodyLine}    ...config,
  });
}`
}

export function generateTsRequestFile(
  operation: ParsedOperation,
  httpClientPath: string,
  typeImportPath: string,
  mergeParams: boolean = false,
  flattenOnGet: boolean = false,
): string {
  const importTypes = [...operation.requestImportTypes, operation.responseTypeName, 'RequestConfig'].filter(
    (value, index, array): value is string => Boolean(value) && array.indexOf(value) === index,
  )
  const importLine = importTypes.length
    ? `import type { ${importTypes.join(', ')} } from ${JSON.stringify(typeImportPath)};\n`
    : ''
  const buildUrlHelper = operation.pathParams.length
    ? `
function buildUrl(path?: Record<string, any>): string {
  return ${JSON.stringify(operation.requestPath)}.replace(/\\{([^}]+)\\}/g, (_, key) => String(path?.[key] ?? ''));
}
`
    : ''

  return `/* eslint-disable */
// Auto-generated by swgto.
import request from ${JSON.stringify(httpClientPath)};
${importLine}
${buildUrlHelper}
${renderFunction(operation, false, mergeParams, flattenOnGet)}
`
}

export function generateTsModuleFile(
  operations: ParsedOperation[],
  httpClientPath: string,
  typeImportPath: string,
  mergeParams: boolean = false,
  flattenOnGet: boolean = false,
): string {
  const importTypeSet = new Set<string>()
  for (const op of operations) {
    for (const t of op.requestImportTypes) importTypeSet.add(t)
    if (op.responseTypeName) importTypeSet.add(op.responseTypeName)
  }
  importTypeSet.add('RequestConfig')

  const importLine = `import type { ${[...importTypeSet].join(', ')} } from ${JSON.stringify(typeImportPath)};\n`

  const needsBuildUrl = operations.some((op) => op.pathParams.length > 0)
  const buildUrlHelper = needsBuildUrl
    ? `
function buildUrl(url: string, path?: Record<string, unknown>): string {
  return url.replace(/\\{([^}]+)\\}/g, (_, key) => String(path?.[key] ?? ''));
}
`
    : ''

  const functions = operations.map((op) => renderFunction(op, true, mergeParams, flattenOnGet)).join('\n\n')

  return `/* eslint-disable */
// Auto-generated by swgto.
import request from ${JSON.stringify(httpClientPath)};
${importLine}${buildUrlHelper}
${functions}
`
}
